remote_theme: just-the-docs/just-the-docs
title: CAPP Camp 2023
color_scheme: uchicago
callouts:
  note:
    title: Note
    color: blue
  warning:
    title: Warning
    color: red
  tip:
    title: Tip
    color: green
